/-
Copyright (c) 2026 Salvatore Mercuri. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Salvatore Mercuri
-/
import SpecialValues.Deligne.GL1.Galois
import Mathlib.FieldTheory.AlgebraicClosure
import PadicLFunctions.Interpolation.GenBernoulli

/-!
# GL(1): the field of values of a Dirichlet character

The value field of the Artin motive of a Dirichlet character `χ` is `ℚ(χ)`, the field generated
over `ℚ` by the values of `χ`. This file defines it, shows it consists of algebraic numbers and
transports along the Galois action — the two requirements `Deligne.Pkg` places on a value field
— and records that the generalised Bernoulli numbers `B_{k,χ}` lie in it and transport along the
action too, which is what the non-positive half of the GL(1) case reduces to.

## Main definitions

* `Deligne.GL1.valueField`: the intermediate field `ℚ(χ)` of `ℂ` generated by the values of `χ`.

## Main results

* `Deligne.GL1.isAlgebraic_of_mem_valueField`: `ℚ(χ)` consists of algebraic numbers.
* `Deligne.GL1.valueField_galoisConj`: `ℚ(χ ^ σ) = σ(ℚ(χ))`.
* `Deligne.GL1.valueField_inv`: `ℚ(χ⁻¹) = ℚ(χ)`.
* `DirichletCharacter.genBernoulli_eq_ratCast_mul_sum`: `B_{k,χ}` as an explicitly rational
  combination of the values of `χ`, whence `Deligne.GL1.genBernoulli_mem_valueField` and
  `Deligne.GL1.genBernoulli_galoisConj`.
-/

open Complex DirichletCharacter ZMod

namespace DirichletCharacter

/-- The generalised Bernoulli number `B_{k,χ}` as an explicitly rational combination of the
values of `χ`. -/
lemma genBernoulli_eq_ratCast_mul_sum {L : Type*} [Field L] [CharZero L] {N : ℕ} [NeZero N]
    (χ : DirichletCharacter L N) (k : ℕ) :
    χ.genBernoulli k = (((N : ℚ) ^ ((k : ℤ) - 1) : ℚ) : L) *
      ∑ a ∈ Finset.range N, χ (a + 1 : ℕ) *
        ((Polynomial.eval (((a : ℚ) + 1) / (N : ℚ)) (Polynomial.bernoulli k) : ℚ) : L) := by
  have key : ∀ q : ℚ, Polynomial.eval (q : L) ((Polynomial.bernoulli k).map (algebraMap ℚ L))
      = ((Polynomial.eval q (Polynomial.bernoulli k) : ℚ) : L) := fun q ↦ by
    rw [Polynomial.eval_map_algebraMap, ← eq_ratCast (algebraMap ℚ L) q,
      Polynomial.aeval_algebraMap_apply_eq_algebraMap_eval, eq_ratCast]
  rw [DirichletCharacter.genBernoulli, Rat.cast_zpow, Rat.cast_natCast]
  congr 1
  refine Finset.sum_congr rfl fun a _ ↦ ?_
  congr 1
  rw [← key]
  congr 1
  push_cast
  ring

end DirichletCharacter

namespace Deligne.GL1

variable {N : ℕ}

/-- The field `ℚ(χ)` generated by the values of a Dirichlet character. -/
noncomputable abbrev valueField (χ : DirichletCharacter ℂ N) : IntermediateField ℚ ℂ :=
  .adjoin ℚ (Set.range χ)

/-- The values of a Dirichlet character are algebraic (`DirichletCharacter.isAlgebraic_apply`),
so the field they generate consists of algebraic numbers. -/
lemma isAlgebraic_of_mem_valueField [NeZero N] (χ : DirichletCharacter ℂ N) {x : ℂ}
    (hx : x ∈ valueField χ) : IsAlgebraic ℚ x :=
  IntermediateField.isAlgebraic_iff.mp <|
    ((IntermediateField.isAlgebraic_adjoin_iff_isAlgebraic ℚ ℂ).mpr
      (by rintro _ ⟨a, rfl⟩; exact χ.isAlgebraic_apply a)).isAlgebraic ⟨x, hx⟩

lemma valueField_galoisConj (σ : Gal(ℂ/ℚ)) (χ : DirichletCharacter ℂ N) :
    valueField (galoisConj χ σ) = (valueField χ).map σ := by
  rw [valueField, valueField, coe_galoisConj, Set.range_comp, IntermediateField.adjoin_map,
    AlgEquiv.coe_toAlgHom]

lemma valueField_inv (χ : DirichletCharacter ℂ N) : valueField χ⁻¹ = valueField χ := by
  have h : ∀ ψ : DirichletCharacter ℂ N, valueField ψ⁻¹ ≤ valueField ψ := by
    intro ψ
    refine IntermediateField.adjoin_le_iff.mpr ?_
    rintro _ ⟨a, rfl⟩
    rw [MulChar.inv_apply_eq_inv']
    exact inv_mem (IntermediateField.subset_adjoin ℚ _ ⟨a, rfl⟩)
  exact le_antisymm (h χ) (by simpa using h χ⁻¹)

/-- The generalised Bernoulli numbers of `χ` lie in the field `ℚ(χ)` generated by its values. -/
lemma genBernoulli_mem_valueField [NeZero N] (χ : DirichletCharacter ℂ N) (k : ℕ) :
    χ.genBernoulli k ∈ valueField χ := by
  rw [DirichletCharacter.genBernoulli_eq_ratCast_mul_sum]
  exact mul_mem (SubfieldClass.ratCast_mem _ _) (sum_mem fun a _ ↦
    mul_mem (IntermediateField.subset_adjoin ℚ _ ⟨_, rfl⟩) (SubfieldClass.ratCast_mem _ _))

/-- The generalised Bernoulli numbers transport along the Galois action. -/
lemma genBernoulli_galoisConj [NeZero N] (χ : DirichletCharacter ℂ N) (σ : Gal(ℂ/ℚ)) (k : ℕ) :
    (galoisConj χ σ).genBernoulli k = σ (χ.genBernoulli k) := by
  simp only [DirichletCharacter.genBernoulli_eq_ratCast_mul_sum, map_mul, map_sum, map_ratCast,
    galoisConj_apply]

end Deligne.GL1
